# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon('favicon.ico'))
        MainWindow.resize(800, 900)
        MainWindow.setMinimumSize(QtCore.QSize(800, 900))
        MainWindow.setMaximumSize(QtCore.QSize(800, 900))
        MainWindow.setBaseSize(QtCore.QSize(800, 900))
        MainWindow.setStyleSheet("background-color: #404041;\n"
"border: 2px solid #b48c50;\n"
"border-radius: 20px;\n"
"font-family: Times New Roman, Bold;\n"
"color: #b48c50;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 900))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 900))
        self.centralwidget.setBaseSize(QtCore.QSize(800, 900))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 30, 761, 851))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(700, 100))
        self.label.setMaximumSize(QtCore.QSize(700, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: #b48c50;\n"
"font-family: Times New Roman;\n"
"font-size: 40pt;\n"
"font-weight: bold;")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(700, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: #505052;\n"
"color: #b48c50;\n"
"border: 1px solid #b48c50;\n"
"border-radius: 3px;\n"
"padding: 5px;\n"
"font-family: Times New Roman;\n"
"font-size: 14px;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(700, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setStyleSheet("border: 1px solid #b48c50;\n"
"border-radius: 3px;\n"
"text-align: center;\n"
"background-color: #505052;\n"
"color: #b48c50;\n"
"font-family: Times New Roman;\n"
"font-size: 12px;\n"
"QProgressBar::chunk {\n"
"    background-color: #b48c50;\n"
"    border-radius: 2px;\n"
"}")
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(50, 58, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 30))
        self.label_4.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
"border: none;\n"
"border-radius: none;\n"
"font-family: Times New Roman, Bold;\n"
"color: #b48c50;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.loginInput = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginInput.sizePolicy().hasHeightForWidth())
        self.loginInput.setSizePolicy(sizePolicy)
        self.loginInput.setMinimumSize(QtCore.QSize(400, 30))
        self.loginInput.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(14)
        self.loginInput.setFont(font)
        self.loginInput.setStyleSheet("background-color: #505052;\n"
"color: #b48c50;\n"
"border: 1px solid #b48c50;\n"
"border-radius: 3px;\n"
"padding: 5px;\n"
"font-family: Times New Roman;\n"
"font-size: 14px;")
        self.loginInput.setObjectName("loginInput")
        self.horizontalLayout.addWidget(self.loginInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 30))
        self.label_5.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: none;\n"
"border: none;\n"
"border-radius: none;\n"
"font-family: Times New Roman, Bold;\n"
"color: #b48c50;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.passwordInput = QtWidgets.QLineEdit(self.widget)
        self.passwordInput.setMinimumSize(QtCore.QSize(400, 30))
        self.passwordInput.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(14)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("background-color: #505052;\n"
"color: #b48c50;\n"
"border: 1px solid #b48c50;\n"
"border-radius: 3px;\n"
"padding: 5px;\n"
"font-family: Times New Roman;\n"
"font-size: 14px;")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.horizontalLayout_2.addWidget(self.passwordInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.parseButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parseButton.sizePolicy().hasHeightForWidth())
        self.parseButton.setSizePolicy(sizePolicy)
        self.parseButton.setMinimumSize(QtCore.QSize(0, 45))
        self.parseButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(14)
        self.parseButton.setFont(font)
        self.parseButton.setToolTipDuration(7)
        self.parseButton.setStyleSheet("""
            QPushButton {
                background-color: #505052;
                color: #b48c50;
                border: 2px solid #b48c50;
                border-radius: 10px;
                padding: 8px 15px;
                font-family: Times New Roman;
                font-size: 14px;
            }
            QPushButton:hover {
                background-color: #b48c50;
                color: #404041;
                border: 2px solid #b48c50;
            }
            QPushButton:pressed {
                background-color: #a07c40;
                color: #404041;
                border: 2px solid #a07c40;
            }
            QPushButton:disabled {
                background-color: #606062;
                color: #807c70;
                border: 2px solid #807c70;
            }
        """)
        self.parseButton.setObjectName("parseButton")
        self.verticalLayout_4.addWidget(self.parseButton)
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 45))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman,12")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: none;\n"
"border: none;\n"
"border-radius: none;\n"
"font-family: Times New Roman, Bold;\n"
"color: #b48c50;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 500))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 500))
        self.textEdit.setStyleSheet("background-color: #505052;\n"
"color: #b48c50;\n"
"border: 1px solid #b48c50;\n"
"border-radius: 3px;\n"
"padding: 5px;\n"
"font-family: Times New Roman;\n"
"font-size: 14px;")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.loginInput)
        MainWindow.setTabOrder(self.loginInput, self.passwordInput)
        MainWindow.setTabOrder(self.passwordInput, self.parseButton)
        MainWindow.setTabOrder(self.parseButton, self.textEdit)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ORO Enumerator"))
        self.label.setText(_translate("MainWindow", "ORO Enumerator"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Ссылка на список задач в ORO:"))
        self.label_4.setText(_translate("MainWindow", "Логин:"))
        self.loginInput.setPlaceholderText(_translate("MainWindow", "Введите логин..."))
        self.label_5.setText(_translate("MainWindow", "Пароль:"))
        self.passwordInput.setPlaceholderText(_translate("MainWindow", "Введите пароль..."))
        self.parseButton.setText(_translate("MainWindow", "Начать\n"
"парсинг"))
        self.label_6.setText(_translate("MainWindow", "Ваши креды\n"
"не сохраняются"))
