# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(619, 433)
        SplashScreen.setWindowTitle("")
        SplashScreen.setStyleSheet("background-color: #404041;\n"
"border: 2px solid #b48c50;\n"
"border-radius: 20px;\n"
"font-family: Times New Roman, Bold;\n"
"color: #b48c50;\n"
"")
        self.widget = QtWidgets.QWidget(SplashScreen)
        self.widget.setGeometry(QtCore.QRect(20, 20, 581, 391))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.widget)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"color: #b48c50;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;\n"
"border: 0;\n"
"border-radius: 0;\n"
"color: #b48c50;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"border: 0;\n"
"border-radius: 0;\n"
"color: #b48c50;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
"border: 0;\n"
"border-radius: 0;\n"
"color: #b48c50;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("SplashScreen", "ORO Enumerator"))
        self.label_3.setText(_translate("SplashScreen", "Разработчик - Чернышов Н.Э."))
        self.label_2.setText(_translate("SplashScreen", "n.chernishov@gmail.com"))
        self.label_4.setText(_translate("SplashScreen", "version 1.2-free/10.2025"))


class AnimatedSplashScreen(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.ui = Ui_SplashScreen()
        self.ui.setupUi(self)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.ui.titleLabel.setStyleSheet("""
            background-color: transparent;
            border: none;
            color: #b48c50;
            font-family: Times New Roman;
            font-size: 45pt;
            font-weight: bold;
        """)
